### PR TITLE
benchmark documentation 

### PR DESCRIPTION
**Pull request by aliciatang07**

### CODE REVIEW

**Review by jungkumseok — CHANGES_REQUESTED** [review]
Sorry, I can't merge this as it contains old code that should not be committed (dashboard v1). Please create a clean pull request containing just the things that should be merged.

Easiest way to do this would be to create a new branch from `dev`, copy the new files to commit, then create a pull request. Thanks!

**Comment by aliciatang07** [comment]
I just made merge from dev before pull requests, I don't think I have old version dashboard anymore?

**Comment by jungkumseok** [comment]
merging `dev` into your branch does not mean your branch is automatically synchronized with `dev`; it will just update the files on your local branch that were affected by recent commits. In your codebase you have files that should not be in the `dev` branch. Please make commits selectively - e.g. `git add /samples/IoTBench/` - instead of doing `git add .`

On another note, I think there are too many levels of indirection in "samples/IoTBench/worker" - why do we need a shell script that spawns yet another node process that spawns yet another things-js worker? Do you think you can iron this out also?

**Comment by aliciatang07** [comment]
ok sure, I will recreate a pull request. 
I am still working on the refactor of IoTBenchmark, I will remove the whole worker folder later, it should go to the user side.

**Comment by jungkumseok** [comment]
merging #32 and not this one

**Pull request closed without merging**
